/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as ChatSettingsRouteImport } from './routes/_chat.settings'
import { Route as ChatPullRequestsRouteImport } from './routes/_chat.pull-requests'
import { Route as ChatPluginsRouteImport } from './routes/_chat.plugins'
import { Route as ChatThreadIdRouteImport } from './routes/_chat.$threadId'
import { Route as ChatStudioIndexRouteImport } from './routes/_chat.studio.index'
import { Route as ChatPullRequestsIndexRouteImport } from './routes/_chat.pull-requests.index'

const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatSettingsRoute = ChatSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ChatRoute,
} as any)
const ChatPullRequestsRoute = ChatPullRequestsRouteImport.update({
  id: '/pull-requests',
  path: '/pull-requests',
  getParentRoute: () => ChatRoute,
} as any)
const ChatPluginsRoute = ChatPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => ChatRoute,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatStudioIndexRoute = ChatStudioIndexRouteImport.update({
  id: '/studio/',
  path: '/studio/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatPullRequestsIndexRoute = ChatPullRequestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatPullRequestsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/$threadId': typeof ChatThreadIdRoute
  '/plugins': typeof ChatPluginsRoute
  '/pull-requests': typeof ChatPullRequestsRouteWithChildren
  '/settings': typeof ChatSettingsRoute
  '/pull-requests/': typeof ChatPullRequestsIndexRoute
  '/studio/': typeof ChatStudioIndexRoute
}
export interface FileRoutesByTo {
  '/$threadId': typeof ChatThreadIdRoute
  '/plugins': typeof ChatPluginsRoute
  '/settings': typeof ChatSettingsRoute
  '/': typeof ChatIndexRoute
  '/pull-requests': typeof ChatPullRequestsIndexRoute
  '/studio': typeof ChatStudioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/_chat/$threadId': typeof ChatThreadIdRoute
  '/_chat/plugins': typeof ChatPluginsRoute
  '/_chat/pull-requests': typeof ChatPullRequestsRouteWithChildren
  '/_chat/settings': typeof ChatSettingsRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/pull-requests/': typeof ChatPullRequestsIndexRoute
  '/_chat/studio/': typeof ChatStudioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$threadId'
    | '/plugins'
    | '/pull-requests'
    | '/settings'
    | '/pull-requests/'
    | '/studio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$threadId'
    | '/plugins'
    | '/settings'
    | '/'
    | '/pull-requests'
    | '/studio'
  id:
    | '__root__'
    | '/_chat'
    | '/_chat/$threadId'
    | '/_chat/plugins'
    | '/_chat/pull-requests'
    | '/_chat/settings'
    | '/_chat/'
    | '/_chat/pull-requests/'
    | '/_chat/studio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/settings': {
      id: '/_chat/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ChatSettingsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/pull-requests': {
      id: '/_chat/pull-requests'
      path: '/pull-requests'
      fullPath: '/pull-requests'
      preLoaderRoute: typeof ChatPullRequestsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/plugins': {
      id: '/_chat/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof ChatPluginsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/$threadId': {
      id: '/_chat/$threadId'
      path: '/$threadId'
      fullPath: '/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/studio/': {
      id: '/_chat/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof ChatStudioIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/pull-requests/': {
      id: '/_chat/pull-requests/'
      path: '/'
      fullPath: '/pull-requests/'
      preLoaderRoute: typeof ChatPullRequestsIndexRouteImport
      parentRoute: typeof ChatPullRequestsRoute
    }
  }
}

interface ChatPullRequestsRouteChildren {
  ChatPullRequestsIndexRoute: typeof ChatPullRequestsIndexRoute
}

const ChatPullRequestsRouteChildren: ChatPullRequestsRouteChildren = {
  ChatPullRequestsIndexRoute: ChatPullRequestsIndexRoute,
}

const ChatPullRequestsRouteWithChildren =
  ChatPullRequestsRoute._addFileChildren(ChatPullRequestsRouteChildren)

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatPluginsRoute: typeof ChatPluginsRoute
  ChatPullRequestsRoute: typeof ChatPullRequestsRouteWithChildren
  ChatSettingsRoute: typeof ChatSettingsRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ChatStudioIndexRoute: typeof ChatStudioIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatPluginsRoute: ChatPluginsRoute,
  ChatPullRequestsRoute: ChatPullRequestsRouteWithChildren,
  ChatSettingsRoute: ChatSettingsRoute,
  ChatIndexRoute: ChatIndexRoute,
  ChatStudioIndexRoute: ChatStudioIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
